// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MelodicCell", "symbols": ["Splits"], "postprocess": id},
    {"name": "Splits", "symbols": ["Splits", "__", "Bar", "__", "Notes"], "postprocess": data => {return data.flat().filter(item => item !== null); }},
    {"name": "Splits", "symbols": ["Notes"], "postprocess": id},
    {"name": "Notes", "symbols": ["Notes", "_", "Note"], "postprocess": data => {return data.flat().filter(item => item !== null); }},
    {"name": "Notes", "symbols": ["Note"]},
    {"name": "Notes", "symbols": [], "postprocess": data => {return [{type:'Blank'}] }},
    {"name": "Note$ebnf$1", "symbols": []},
    {"name": "Note$ebnf$1", "symbols": ["Note$ebnf$1", /[/]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Note", "symbols": ["Note$ebnf$1", "Solfege"], "postprocess": data => {return {type:'Note', solfege: data[1][0], octave: -data[0].length}}},
    {"name": "Note$ebnf$2", "symbols": [/[\\]/]},
    {"name": "Note$ebnf$2", "symbols": ["Note$ebnf$2", /[\\]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Note", "symbols": ["Note$ebnf$2", "Solfege"], "postprocess": data => {return {type:'Note', solfege: data[1][0], octave: data[0].length}}},
    {"name": "Note$ebnf$3", "symbols": []},
    {"name": "Note$ebnf$3", "symbols": ["Note$ebnf$3", /[/]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Note", "symbols": ["Note$ebnf$3", "ScaleDegree"], "postprocess": data => {return {type:'Note', scaleDegree: data[1], octave: -data[0].length}}},
    {"name": "Note$ebnf$4", "symbols": [/[\\]/]},
    {"name": "Note$ebnf$4", "symbols": ["Note$ebnf$4", /[\\]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Note", "symbols": ["Note$ebnf$4", "ScaleDegree"], "postprocess": data => {return {type:'Note', scaleDegree: data[1], octave: data[0].length}}},
    {"name": "Note$ebnf$5", "symbols": []},
    {"name": "Note$ebnf$5", "symbols": ["Note$ebnf$5", /[/]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Note", "symbols": ["Note$ebnf$5", "Spelling"], "postprocess": data => {return {type:'Note', spelling: data[1], octave: -data[0].length}}},
    {"name": "Note$ebnf$6", "symbols": [/[\\]/]},
    {"name": "Note$ebnf$6", "symbols": ["Note$ebnf$6", /[\\]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Note", "symbols": ["Note$ebnf$6", "Spelling"], "postprocess": data => {return {type:'Note', spelling: data[1], octave: data[0].length}}},
    {"name": "Note", "symbols": [{"literal":"_"}], "postprocess": _ => {return {type:'Blank'}}},
    {"name": "Note", "symbols": [{"literal":"-"}], "postprocess": _ => {return {type:'Slot'}}},
    {"name": "Note", "symbols": [{"literal":"x"}], "postprocess": _ => {return {type:'Rest'}}},
    {"name": "scaleNumber", "symbols": [/[1-7]/], "postprocess": data => { return parseInt(data[0]); }},
    {"name": "ScaleDegree$ebnf$1", "symbols": []},
    {"name": "ScaleDegree$ebnf$1", "symbols": ["ScaleDegree$ebnf$1", /[b]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ScaleDegree", "symbols": ["ScaleDegree$ebnf$1", "scaleNumber"], "postprocess": data => {return {numSharps: -data[0].length, scaleNumber: data[1]}}},
    {"name": "ScaleDegree$ebnf$2", "symbols": [/[#]/]},
    {"name": "ScaleDegree$ebnf$2", "symbols": ["ScaleDegree$ebnf$2", /[#]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ScaleDegree", "symbols": ["ScaleDegree$ebnf$2", "scaleNumber"], "postprocess": data => {return {numSharps: data[0].length, scaleNumber: data[1]}}},
    {"name": "Spelling$ebnf$1", "symbols": []},
    {"name": "Spelling$ebnf$1", "symbols": ["Spelling$ebnf$1", /[b]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Spelling", "symbols": ["Letter", "Spelling$ebnf$1"], "postprocess": data => {return {letter: data[0], numSharps: -data[1].length}}},
    {"name": "Spelling$ebnf$2", "symbols": [/[#]/]},
    {"name": "Spelling$ebnf$2", "symbols": ["Spelling$ebnf$2", /[#]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Spelling", "symbols": ["Letter", "Spelling$ebnf$2"], "postprocess": data => {return {letter: data[0], numSharps: data[1].length}}},
    {"name": "Letter", "symbols": [/[a-gA-G]/], "postprocess": data => {return data[0].toUpperCase() }},
    {"name": "Solfege$string$1", "symbols": [{"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$1"]},
    {"name": "Solfege$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$2"]},
    {"name": "Solfege$string$3", "symbols": [{"literal":"d"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$3"]},
    {"name": "Solfege$string$4", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$4"]},
    {"name": "Solfege$string$5", "symbols": [{"literal":"d"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$5"]},
    {"name": "Solfege$string$6", "symbols": [{"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$6"]},
    {"name": "Solfege$string$7", "symbols": [{"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$7"]},
    {"name": "Solfege$string$8", "symbols": [{"literal":"r"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$8"]},
    {"name": "Solfege$string$9", "symbols": [{"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$9"]},
    {"name": "Solfege$string$10", "symbols": [{"literal":"r"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$10"]},
    {"name": "Solfege$string$11", "symbols": [{"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$11"]},
    {"name": "Solfege$string$12", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$12"]},
    {"name": "Solfege$string$13", "symbols": [{"literal":"m"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$13"]},
    {"name": "Solfege$string$14", "symbols": [{"literal":"m"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$14"]},
    {"name": "Solfege$string$15", "symbols": [{"literal":"m"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$15"]},
    {"name": "Solfege$string$16", "symbols": [{"literal":"f"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$16"]},
    {"name": "Solfege$string$17", "symbols": [{"literal":"f"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$17"]},
    {"name": "Solfege$string$18", "symbols": [{"literal":"f"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$18"]},
    {"name": "Solfege$string$19", "symbols": [{"literal":"f"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$19"]},
    {"name": "Solfege$string$20", "symbols": [{"literal":"f"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$20"]},
    {"name": "Solfege$string$21", "symbols": [{"literal":"s"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$21"]},
    {"name": "Solfege$string$22", "symbols": [{"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$22"]},
    {"name": "Solfege$string$23", "symbols": [{"literal":"s"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$23"]},
    {"name": "Solfege$string$24", "symbols": [{"literal":"s"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$24"]},
    {"name": "Solfege$string$25", "symbols": [{"literal":"s"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$25"]},
    {"name": "Solfege$string$26", "symbols": [{"literal":"l"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$26"]},
    {"name": "Solfege$string$27", "symbols": [{"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$27"]},
    {"name": "Solfege$string$28", "symbols": [{"literal":"l"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$28"]},
    {"name": "Solfege$string$29", "symbols": [{"literal":"l"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$29"]},
    {"name": "Solfege$string$30", "symbols": [{"literal":"l"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$30"]},
    {"name": "Solfege$string$31", "symbols": [{"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$31"]},
    {"name": "Solfege$string$32", "symbols": [{"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$32"]},
    {"name": "Solfege$string$33", "symbols": [{"literal":"t"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$33"]},
    {"name": "Solfege$string$34", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$34"]},
    {"name": "Solfege$string$35", "symbols": [{"literal":"t"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Solfege", "symbols": ["Solfege$string$35"]},
    {"name": "Bar", "symbols": [{"literal":"|"}], "postprocess": _ => {return {type:'Bar'}}},
    {"name": "Bar", "symbols": [{"literal":";"}], "postprocess": _ => {return {type:'GuideBar'}}},
    {"name": "_$ebnf$1", "symbols": [/[ ]/]},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[ ]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": data => {return null }},
    {"name": "__$ebnf$1", "symbols": []},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", /[ ]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": data => {return null }}
]
  , ParserStart: "MelodicCell"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
